/* Course survey: coordinates remain in the tracker only; persisted checkpoints contain totals. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),track=new SurveyTracking.Tracker();
 let baseline=null,target=null,startedLabel='',savedBusy=false,lastPersist=0,dirty=false,proposal=false;
 window.SurveyTracker={sample:pos=>{track.sample(pos);render();},error:err=>{const msg={1:'位置情報の許可が必要です',2:'位置情報を取得できません',3:'GPS取得がタイムアウトしました'}[err.code]||'GPS取得失敗';track.break(msg+'：距離に欠落あり');render();persist();}};
 const tab=document.createElement('button');tab.id='tab-course';tab.className='tab-btn';tab.textContent='📏 コース';tab.onclick=()=>showTab('course');document.querySelector('.topbar').insertBefore(tab,$('tab-hist'));
 const section=document.createElement('div');section.id='screen-course';section.className='screen';
 section.innerHTML=`<div class="sec-hdr">コースを選ぶ・作成する</div>
 <div class="form-group"><label class="form-label" for="sv-course-select">調査対象</label><select id="sv-course-select" class="field-in"></select><button id="sv-course-load" class="sv-btn">シートからコースを再読込</button><p id="sv-course-load-status" class="sv-note" role="status"></p></div>
 <div class="form-group"><label class="form-label" for="sv-course-id">コースID</label><input id="sv-course-id" class="field-in mono" placeholder="course_01"><label class="form-label" for="sv-course-name">コース名</label><input id="sv-course-name" class="field-in"><p id="sv-course-info" class="sv-note"></p></div>
 <div class="sec-hdr">現地の移動を計測</div><div class="sv-measure"><div class="sv-metrics"><div><span>採用した移動距離</span><strong id="sv-distance">0 m</strong></div><div><span>計測時間（停止を除く）</span><strong id="sv-active">00:00:00</strong></div><div><span>開始からの総経過</span><strong id="sv-total">00:00:00</strong></div></div><p id="sv-status" role="status"></p><p id="sv-start-label" class="sv-note"></p><p id="sv-incomplete" class="sv-warning"></p><div class="sv-actions"><button id="sv-start" class="sv-btn">調査開始</button><button id="sv-pause" class="sv-btn">一時停止</button><button id="sv-resume" class="sv-btn">再開</button><button id="sv-finish" class="sv-btn">終了</button><button id="sv-cancel" class="sv-btn">リセットして最初から</button></div><p class="sv-note">時間は「調査開始」を押した時点から。距離は最初の有効なGPSから計測します。停止時間を除く時間にも見学・立ち止まりを含みます。</p><p class="sv-warning">画面を表示したままご利用ください。画面消灯・別アプリへの移動では自動的に一時停止します。戻ったら再開してください。取得できなかった区間の距離は補完しません。GPSの誤差により距離は目安です。</p></div>
 <div class="sec-hdr">結果を確認してコースへ反映</div><div class="form-group"><p class="sv-note">終了後に確認して反映してください。既存の値は反映ボタンを押すまで変わりません。</p><label class="form-label" for="sv-time-basis">所要時間に使う値</label><select id="sv-time-basis" class="field-in"><option value="active">計測時間（停止を除く）</option><option value="total">開始からの総経過（停止を含む）</option></select><label class="form-label" for="sv-distance-step">距離の切り上げ幅（m）</label><input id="sv-distance-step" type="number" min="1" value="50" class="field-in"><label class="form-label" for="sv-duration-step">時間の切り上げ幅（分）</label><input id="sv-duration-step" type="number" min="1" value="5" class="field-in"><button id="sv-apply" class="sv-btn">結果をフォームへ反映</button><label class="form-label" for="sv-course-distance">距離（m）</label><input id="sv-course-distance" type="number" min="0" step="1" class="field-in"><label class="form-label" for="sv-course-duration">所要時間（分）</label><input id="sv-course-duration" type="number" min="0" step="0.1" class="field-in"><button id="sv-draft-save" class="sv-btn">端末に下書きを保存</button><label class="form-label" for="sv-write-token">書き込みトークン（エディターの設定と同じ）</label><input id="sv-write-token" type="password" autocomplete="off" class="field-in" placeholder="この画面の間だけ使用"><p class="sv-note">トークンは端末保存せず、確認後のGAS送信だけに使用します。</p><button id="sv-cloud-save" class="sv-btn">確認してシートへ送信</button><p id="sv-save-status" class="sv-note" role="status"></p><p class="sv-note">新規コースは未公開で作成します。スポットの順序・公開設定はエディターで設定してください。送信先は既存の設定を使用します。GPS位置履歴は保存・送信しません。</p></div>`;
 document.querySelector('.content').appendChild(section);
 S.courses=lsj('courses')||[];S.course_spots=lsj('course_spots')||[];
 function options(){const id=$('sv-course-select').value;$('sv-course-select').innerHTML='<option value="">新しいコース</option>'+S.courses.map(c=>'<option value="'+esc(c.course_id)+'">'+esc(c.course_name||c.course_id)+'</option>').join('');if(S.courses.some(c=>c.course_id===id))$('sv-course-select').value=id;}
 function choose(){const row=S.courses.find(c=>c.course_id===$('sv-course-select').value);baseline=row?{...row}:null;target=row?.course_id||null;$('sv-course-id').value=row?.course_id||'';$('sv-course-id').readOnly=!!row;$('sv-course-name').value=row?.course_name||'';$('sv-course-name').readOnly=!!row;$('sv-course-distance').value=row?.distance_m||'';$('sv-course-duration').value=row?.duration_min||'';$('sv-course-info').textContent=row?'既存値：'+(row.distance_m||'未設定')+' m / '+(row.duration_min||'未設定')+' 分。登録スポット '+S.course_spots.filter(x=>x.course_id===row.course_id).length+' 件':'新規コースのIDと名前を入力してください';dirty=false;}
 function validCourse(){const id=$('sv-course-id').value.trim(),name=$('sv-course-name').value.trim();if(!/^[a-z][a-z0-9_]*$/.test(id)||!name)throw Error('コースID（小文字英数字・_、先頭は英字）と名前を入力してください');return id;}
 function persist(){const s=track.snapshot();try{localStorage.setItem('sv_measure',JSON.stringify({...s,startedLabel,target,savedAt:Date.now()}));}catch{}lastPersist=performance.now();}
 function render(){const s=track.snapshot();$('sv-distance').textContent=Math.round(s.meters)+' m';$('sv-active').textContent=SurveyTracking.duration(s.activeMs);$('sv-total').textContent=SurveyTracking.duration(s.totalMs);$('sv-status').textContent=({idle:'未開始',running:'計測中',paused:'一時停止',finished:'終了'})[s.state]+' — '+s.message;$('sv-start-label').textContent=startedLabel?'開始：'+startedLabel:'';$('sv-incomplete').textContent=s.interruptions?'距離に欠落の可能性があります（区間切断 '+s.interruptions+' 回）。既知のコース距離と確認してください。':'';
 for(const [id,on] of [['sv-start',s.state==='idle'],['sv-pause',s.state==='running'],['sv-resume',s.state==='paused'],['sv-finish',['running','paused'].includes(s.state)],['sv-cancel',s.state!=='idle'],['sv-apply',s.state==='finished']])$(id).disabled=!on;
 $('sv-course-select').disabled=['running','paused'].includes(s.state);$('sv-course-load').disabled=['running','paused'].includes(s.state)||savedBusy;$('sv-course-id').disabled=['running','paused'].includes(s.state);$('sv-cloud-save').disabled=savedBusy;}
 $('sv-course-select').onchange=()=>{if(track.state!=='idle'){if(!confirm('計測結果を取り消して対象を変更しますか？')){$('sv-course-select').value=target||'';return;}track.reset();startedLabel='';persist();}choose();render();};
 $('sv-start').onclick=()=>{try{target=validCourse();if(!navigator.geolocation)throw Error('このブラウザーはGPSに対応していません');if(!track.start())return;startedLabel=new Date().toLocaleString();render();persist();}catch(e){toast(e.message,'err');}};
 for(const [id,method] of [['sv-pause','pause'],['sv-resume','resume'],['sv-finish','finish']])$(id).onclick=()=>{track[method]();render();persist();};
 $('sv-cancel').onclick=()=>{if(!confirm('現在の計測をリセットして最初からやり直しますか？既存コースと保存済み下書きは消しません。'))return;track.reset();startedLabel='';if(proposal){$('sv-course-distance').value=baseline?.distance_m||'';$('sv-course-duration').value=baseline?.duration_min||'';proposal=false;dirty=false;$('sv-save-status').textContent='計測と今回の案内値提案をリセットしました。';}render();persist();};
 $('sv-apply').onclick=()=>{try{if(track.state!=='finished'||validCourse()!==target)throw Error('計測した対象コースを確認してください');const s=track.snapshot();const meters=SurveyTracking.roundUp(s.meters,Number($('sv-distance-step').value));const minutes=SurveyTracking.roundUp(($('sv-time-basis').value==='total'?s.totalMs:s.activeMs)/60000,Number($('sv-duration-step').value));if(!confirm('実測 '+Math.round(s.meters)+' m を案内値 '+meters+' m、時間を '+minutes+' 分としてフォームへ反映します。'+(s.interruptions?'距離に欠落がある結果です。':'')))return;$('sv-course-distance').value=meters;$('sv-course-duration').value=minutes;dirty=true;proposal=true;$('sv-save-status').textContent='案内値をフォームへ反映しました。手修正できます。実測値は端末内に保持し、シートは未変更です。';persist();}catch(e){toast(e.message,'err');}};
 function draft(){const id=validCourse();for(const key of ['distance','duration']){const v=$('sv-course-'+key).value;if(v===''||!Number.isFinite(Number(v))||Number(v)<0)throw Error('距離と時間に0以上の数値を入力してください');}return {...(baseline||{course_type:'市街地',display_order:'99',recommended:'FALSE',is_published:'FALSE'}),course_id:id,course_name:$('sv-course-name').value.trim(),distance_m:$('sv-course-distance').value,duration_min:$('sv-course-duration').value};}
 $('sv-draft-save').onclick=()=>{try{const d=draft();lsj('course_draft',d);$('sv-save-status').textContent='この端末に下書きを保存しました。シートの値は変更していません。';dirty=false;}catch(e){toast(e.message,'err');}};
 async function load(){if(dirty&&!confirm('未保存のフォームを破棄して再読込しますか？'))return;if(!S.sheetId){$('sv-course-load-status').textContent='設定タブでシートIDを設定してください';return;}try{const [courses,spots]=await Promise.all([fetchGviz(S.sheetId,'courses'),fetchGviz(S.sheetId,'course_spots')]);S.courses=SurveyTracking.parseCourseCsv(courses);S.course_spots=SurveyTracking.parseCourseCsv(spots);lsj('courses',S.courses);lsj('course_spots',S.course_spots);options();choose();$('sv-course-load-status').textContent='コースを読み込みました';}catch(e){$('sv-course-load-status').textContent=e.message;}}
 $('sv-course-load').onclick=load;
 $('sv-cloud-save').onclick=async()=>{if(savedBusy)return;try{const d=draft();if(!S.sheetId||!S.gasUrl)throw Error('設定タブでシートIDとGAS URLを設定してください');if(!/^https:\/\/script\.google\.com\/macros\/s\/[a-zA-Z0-9_-]+\/exec$/.test(S.gasUrl))throw Error('GASの正規デプロイURLを設定してください');const token=$('sv-write-token').value.trim();if(!token)throw Error('エディターで設定した書き込みトークンを入力してください');if(!confirm('コース「'+d.course_name+'」の距離 '+d.distance_m+' m・所要時間 '+d.duration_min+' 分をシートへ送信します。'+(baseline?'既存の距離・時間を置き換えます。':'新規・未公開で作成します。')))return;savedBusy=true;render();const rows=SurveyTracking.parseCourseCsv(await fetchGviz(S.sheetId,'courses'));const merged=SurveyTracking.mergeCourse(rows,d,baseline);await fetch(S.gasUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'write',sheet:'courses',rows:merged,token})});$('sv-save-status').textContent='送信しましたが保存結果は未確認です。「再読込」でシートの値を確認してください。下書きは保持しています。';lsj('course_draft',d);dirty=false;}catch(e){$('sv-save-status').textContent='送信できませんでした：'+e.message;}finally{savedBusy=false;render();}};
 for(const id of ['sv-course-id','sv-course-name','sv-course-distance','sv-course-duration'])$(id).addEventListener('input',()=>dirty=true);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&track.state==='running')track.pause('画面が非表示になりました。距離に欠落あり。戻ったら再開してください');render();persist();});
 window.addEventListener('beforeunload',e=>{if(['running','paused'].includes(track.state)||dirty){e.preventDefault();e.returnValue='';}persist();});
 options();choose();
 try{const s=JSON.parse(localStorage.getItem('sv_measure')||'null');if(s&&['running','paused','finished'].includes(s.state)&&Number.isFinite(s.totalMs)&&Number.isFinite(s.activeMs)&&Number.isFinite(s.meters)){const n=performance.now(),gap=Math.max(0,Date.now()-s.savedAt);track.state=s.state==='finished'?'finished':'paused';track.started=n-s.totalMs-(track.state==='paused'?gap:0);track.ended=track.state==='finished'?n:null;track.activeMs=s.activeMs;track.meters=s.meters;track.interruptions=(s.interruptions||0)+(s.state==='finished'?0:1);track.message='端末内の結果を復元しました。再読込間の総経過は端末時計に依存する参考値です。再開前に対象を確認してください';startedLabel=s.startedLabel||'';target=s.target||null;if(S.courses.some(c=>c.course_id===target)){$('sv-course-select').value=target;choose();}else{$('sv-course-id').value=target||'';}if(Date.now()<s.savedAt)track.message+='（端末時計の変更：総経過は参考値）';}}
 catch{}const d=lsj('course_draft');if(d&&confirm('端末のコース下書きをフォームに戻しますか？')){if(S.courses.some(c=>c.course_id===d.course_id)){$('sv-course-select').value=d.course_id;choose();}$('sv-course-id').value=d.course_id;$('sv-course-name').value=d.course_name;$('sv-course-distance').value=d.distance_m;$('sv-course-duration').value=d.duration_min;dirty=true;}
 render();setInterval(()=>{render();if(track.state==='running'&&performance.now()-lastPersist>5000)persist();},1000);
})();
