const {test}=require('node:test'),assert=require('node:assert/strict');
const {Tracker,roundUp,duration,mergeCourse,parseCourseCsv}=require('../survey-tracker.js');
const fix=(meters,t,accuracy=5,speed=null)=>({timestamp:t,coords:{latitude:35,longitude:139+meters/(111195*Math.cos(35*Math.PI/180)),accuracy,speed}});
function setup(){let time=0;const t=new Tracker(()=>time);return {t,set:n=>time=n,feed:(m,n,a=5,s=null)=>t.sample(fix(m,n,a,s),n)};}
test('first valid GPS starts distance, repeated start is ignored',()=>{const {t,set,feed}=setup();t.start();set(5000);assert.equal(t.start(),false);assert.equal(t.snapshot().activeMs,5000);feed(0,5000);feed(10,15000);assert.ok(Math.abs(t.meters-10)<.05);});
test('poor accuracy, stale/invalid positions and GPS failure break continuity',()=>{const {t,feed}=setup();t.start();feed(0,0);feed(10,10000,80);feed(100,20000);assert.equal(t.meters,0);t.break('GPS failure');feed(200,30000);assert.equal(t.meters,0);t.sample(fix(210,0),40000);assert.equal(t.anchor,null);assert.ok(t.interruptions>0);});
test('out of order and duplicate fresh positions are not counted',()=>{const {t,feed}=setup();t.start();feed(0,1000);feed(5,1000);feed(5,999);assert.equal(t.meters,0);feed(10,11000);assert.ok(t.meters>9);});
test('jump, high speed and long gaps never bridge',()=>{const {t,feed}=setup();t.start();feed(0,0);feed(1000,1000);feed(1100,11000);assert.equal(t.meters,0);feed(1200,50000);assert.equal(t.meters,0);feed(1210,60000);assert.ok(t.meters>9&&t.meters<11);});
test('stationary GPS jitter does not accumulate with low speed',()=>{const {t,feed}=setup();t.start();for(let i=0;i<20;i++)feed(i%2?5:0,i*10000,5,0);assert.equal(t.meters,0);});
test('pause, resume, finish and cancellation separate active and total',()=>{const {t,set,feed}=setup();t.start();feed(0,0);set(10000);t.pause();set(40000);feed(100,40000);t.resume();feed(100,40000);feed(110,50000);set(50000);t.finish();set(80000);assert.equal(t.snapshot().activeMs,20000);assert.equal(t.snapshot().totalMs,50000);assert.ok(t.meters<11);assert.equal(t.resume(),false);t.reset();assert.equal(t.meters,0);assert.equal(t.state,'idle');});
test('time uses timestamp differences across midnight and more than 24 hours',()=>{const {t,set}=setup();set(86399000);t.start();set(86401000);assert.equal(t.snapshot().activeMs,2000);assert.equal(duration(90061000),'25:01:01');});
test('rounding suggestion is stable at boundaries and zero',()=>{assert.equal(roundUp(187,50),200);assert.equal(roundUp(18,5),20);for(const [v,s] of [[0,50],[200,50],[20,5],[0,5]]){assert.equal(roundUp(v,s),v);assert.equal(roundUp(roundUp(v,s),s),v);}assert.equal(roundUp(200.1,50),250);assert.throws(()=>roundUp(NaN,5));});
test('course merge changes only metrics and protects concurrent changes',()=>{const a={course_id:'old',course_name:'a',distance_m:'100',duration_min:'10',description:'keep',is_published:'TRUE'},b={course_id:'b',distance_m:'200'};const out=mergeCourse([a,b],{course_id:'old',course_name:'bad',distance_m:'200',duration_min:'20'},a);assert.equal(out[0].description,'keep');assert.equal(out[0].course_name,'a');assert.deepEqual(out[1],b);assert.equal(a.distance_m,'100');assert.throws(()=>mergeCourse([{...a,distance_m:'300'}],{course_id:'old'},a));assert.equal(mergeCourse([],{course_id:'new',is_published:'TRUE'},null)[0].is_published,'FALSE');assert.throws(()=>mergeCourse([a],a,null));});
test('course CSV preserves multiline descriptions, commas, quotes and blank fields',()=>{const rows=parseCourseCsv('\uFEFFcourse_id,course_description,custom\r\nold," one\n two, ""quote"" ",\r\nother,plain,x\r\n');assert.equal(rows.length,2);assert.equal(rows[0].course_description,' one\n two, "quote" ');assert.equal(rows[0].custom,'');assert.throws(()=>parseCourseCsv('wrong\na'));assert.throws(()=>parseCourseCsv('course_id\n"unfinished'));});
